data:
  train: "data/libritts-train-clean-100.csv"
  test: "data/libritts-test-clean.csv"
  val: "data/libritts-dev-clean.csv"
  num_workers: 8
  prefetch_factor: 32
model:
  extensions:
    - speaker_embeddings
preprocessing:
  valid_chars: "!'(),.:;? \\-ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
training:
  batch_size: 64
  lr: 0.001
  weight_decay: 0.000001
  devices: 1
  precision: 16
  accelerator: gpu
audio:
  num_mels: 80
encoder:
  encoder_kernel_size: 5
  char_embedding_dim: 512
decoder:
  prenet_dim: 256
  rnn_hidden_dim: 1024
  postnet_dim: 512
attention:
  att_rnn_dim: 1024
  att_dim: 128
tacotron2:
  dropout: 0.5
extensions:
  speaker_embeddings:
    speaker_ids: "data/libritts-speaker-ids.csv"
    num_speakers: 326
    embedding_dim: 64
