data:
  train: "data/ljspeech-train.csv"
  test: "data/ljspeech-test.csv"
  val: "data/ljspeech-dev.csv"
  num_workers: 8
  prefetch_factor: 32
preprocessing:
  valid_chars: "!'(),.:;? \\-ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
training:
  batch_size: 64
  lr: 0.001
  weight_decay: 0.000001
  devices: 1
  precision: 16
  accelerator: gpu
audio:
  num_mels: 80
encoder:
  encoder_kernel_size: 5
  char_embedding_dim: 512
decoder:
  prenet_dim: 256
  rnn_hidden_dim: 1024
  postnet_dim: 512
attention:
  att_rnn_dim: 1024
  att_dim: 128
tacotron2:
  dropout: 0.5
